### ISSUE TITLE
get some errors

### ISSUE THREAD

**Issue by steamgirl2020** [Sorrow446/TOWER-RECORDS-MUSIC-Downloader#1]
X:\TOWER-RECORDS-MUSIC>trm_dl_x64.exe https://music.tower.jp/album/detail/1020615044 https://music.tower.jp/album/detail/1020661108

 _____ _____ _____    ____                _           _
|_   _| __  |     |  |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
  | | |    -| | | |  |  |  | . | | | |   | | . | .'| . | -_|  _|
  |_| |__|__|_|_|_|  |____/|___|_____|_|_|_|___|__,|___|___|_|

panic: Failed to auth.
Bad credentials?

goroutine 1 [running]:
main.handleErr({0x1374162, 0x17}, {0x13e8c60, 0xc000043790}, 0x1)
        G:/go/TOWER-RECORDS-MUSIC-Downloader-main/main.go:75 +0x10b
main.main()
        G:/go/TOWER-RECORDS-MUSIC-Downloader-main/main.go:475 +0x106

X:\TOWER-RECORDS-MUSIC>

**Comment by Sorrow446** [comment]
Send me your credentials please. Need to see where the login post redirects to.

https://www.reddit.com/user/Sorrow446
Sorrow#6826

**Comment by steamgirl2020** [comment]
User doesn't accept direct messages. Try sending a chat request instead.

Why can I not PM/chat on Reddit?
In order to prevent spammers or other types of message abuse, new accounts and accounts with low karma, can't send private messages. However, after you've been on Reddit for a while and you've gained some karma, you'll be able to send private messages.

https://www.reddit.com/chat/user_id/t2_8i2gihef/
https://www.reddit.com/message/compose/?to=steamgirl2020

**Comment by Sorrow446** [comment]
https://github.com/Sorrow446/TOWER-RECORDS-MUSIC-Downloader/commit/0e33003421a8272fcc3fbaf74f8a98f4b58fcc9d
https://anonfiles.com/J0kcf4d7yb/trm_dl_x64_exe
